nnoremap <leader>il :call vimspector#Launch()<CR>
nnoremap <leader>ix :call vimspector#Reset()<CR>
nnoremap <leader>ib :call vimspector#ToggleBreakpoint()<CR>
nnoremap <leader>is :call vimspector#StepInto()<CR>
nnoremap <leader>in :call vimspector#StepOver()<CR>
nnoremap <leader>io :call vimspector#StepOut()<CR>
nnoremap <leader>ic :call vimspector#Continue()<CR>
nnoremap <leader>ir :call vimspector#Restart()<CR>
nnoremap <leader>it :call vimspector#RunToCursor()<CR>
